### ISSUE TITLE
error .. FileNotFoundError: [Errno 2] No such file or directory: 'command'

### ISSUE THREAD

**Issue by odarcan** [djcopley/ShellOracle#31]
I get this when I run the second command

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/__main__.py", line 24, in <module>
    main()
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/__main__.py", line 17, in main
    bootstrap()
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/bootstrap.py", line 79, in bootstrap
    if not (shells := get_installed_shells()):
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/bootstrap.py", line 29, in get_installed_shells
    if subprocess.run(["command", "-v", shell], stdout=subprocess.DEVNULL):
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'command'

**Comment by djcopley** [comment]
@odarcan Hmm that's annoying. What OS/Shell are you using?

**Comment by odarcan** [comment]
I am using mint

**Comment by djcopley** [comment]
@odarcan If you run `command -v ls` in your terminal, what is the output?

**Comment by odarcan** [comment]
output is
**alias ls='ls --color=auto'**
from running "command -v ls"

**Comment by djcopley** [comment]
Just to double check, can you run `python3 -c "import subprocess; subprocess.run(['command', '-v', 'bash'])"`? What does that command return?

**Comment by odarcan** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'command'

**Comment by djcopley** [comment]
Last one: `python3 -c "import subprocess; subprocess.run(['which', 'bash'])"`

**Comment by odarcan** [comment]
result is 
/usr/bin/bash

**Comment by odarcan** [comment]
Im happy to help if you have more questions

**Comment by djcopley** [comment]
Ok I have a temporary fix for you, but I'm still working on figuring out the root cause 🙃

To install the fix run: `pip3 install --upgrade --force git+https://github.com/djcopley/ShellOracle@fix-install-linux-mint`

And then try running `shor --init` again

**Comment by odarcan** [comment]
eh

second command gave this 

Traceback (most recent call last):
  File "/home/x/.local/bin/shor", line 8, in <module>
    sys.exit(main())
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/__main__.py", line 17, in main
    bootstrap()
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/bootstrap.py", line 79, in bootstrap
    if not (shells := get_installed_shells()):
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/bootstrap.py", line 29, in get_installed_shells
    if subprocess.run(["command", "-v", shell], stdout=subprocess.DEVNULL):
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'command'

**Comment by djcopley** [comment]
It looks like it didn't install correctly because that line 29 error no longer exists. Did you run the pip install with the special path I wrote first?

I think I figured out the problem. `command` is a shell built-in which cannot be called from subprocess.run() in some environments.

**Comment by odarcan** [comment]
command **pip3 install --upgrade --force git+https://github.com/djcopley/ShellOracle@fix-install-linux-mint**

gives this:

Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/djcopley/ShellOracle@fix-install-linux-mint
  Cloning https://github.com/djcopley/ShellOracle (to revision fix-install-linux-mint) to /tmp/pip-req-build-uj6krfi1
  Running command git clone --filter=blob:none --quiet https://github.com/djcopley/ShellOracle /tmp/pip-req-build-uj6krfi1
  Running command git checkout -b fix-install-linux-mint --track origin/fix-install-linux-mint
  Switched to a new branch 'fix-install-linux-mint'
  Branch 'fix-install-linux-mint' set up to track remote branch 'fix-install-linux-mint' from 'origin'.
  Resolved https://github.com/djcopley/ShellOracle to commit b83f50a155d98845ab580b752429e3fba33c84df
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.5.1.dev2+gb83f50a-py3-none-any.whl size=13444 sha256=5f86e4a1233f46678a5317954137ac28c3a8dd84b8a23ffd5f724687942bfdec
  Stored in directory: /tmp/pip-ephem-wheel-cache-m30wvif6/wheels/33/bf/d5/81484828533d027636bf6eefa1b804635efcc871e83e1b9ae8
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.5.1.dev2+gb83f50a
    Uninstalling UNKNOWN-0.5.1.dev2+gb83f50a:
      Successfully uninstalled UNKNOWN-0.5.1.dev2+gb83f50a
Successfully installed UNKNOWN-0.5.1.dev2+gb83f50a

**Comment by djcopley** [comment]
Thanks for your patience. I accidentally omitted the .git from the repo, which I think is causing the UNKNOWN name issue?

One final try: `pip3 install --upgrade --force git+https://github.com/djcopley/ShellOracle.git@fix-install-linux-mint`

Fingers crossed this one works 🤞🏻

**Comment by odarcan** [comment]
result, same? : 

Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/djcopley/ShellOracle.git@fix-install-linux-mint
  Cloning https://github.com/djcopley/ShellOracle.git (to revision fix-install-linux-mint) to /tmp/pip-req-build-qla5iem0
  Running command git clone --filter=blob:none --quiet https://github.com/djcopley/ShellOracle.git /tmp/pip-req-build-qla5iem0
  Running command git checkout -b fix-install-linux-mint --track origin/fix-install-linux-mint
  Switched to a new branch 'fix-install-linux-mint'
  Branch 'fix-install-linux-mint' set up to track remote branch 'fix-install-linux-mint' from 'origin'.
  Resolved https://github.com/djcopley/ShellOracle.git to commit b83f50a155d98845ab580b752429e3fba33c84df
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.5.1.dev2+gb83f50a-py3-none-any.whl size=13444 sha256=0dca298687c8967f0b8cf72d0a0a40ba18aa7d4383e0f229adb95cb14b81b9c8
  Stored in directory: /tmp/pip-ephem-wheel-cache-b1dfv7o8/wheels/78/90/b9/b2d4317911342cba1e4fcbdb5f4150a60c5c8ce85ff8264ce6
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.5.1.dev2+gb83f50a
    Uninstalling UNKNOWN-0.5.1.dev2+gb83f50a:
      Successfully uninstalled UNKNOWN-0.5.1.dev2+gb83f50a
Successfully installed UNKNOWN-0.5.1.dev2+gb83f50a

**Comment by djcopley** [comment]
Dang, not sure why pip isn't fetching from the git repo correctly. Here is the new plan. I just published the patch to PYPI, I'm fairly confident it will work. I'm gonna have you completely uninstall ShellOracle and then reinstall.

1. `pip3 uninstall shelloracle`
2. Ensure it is uninstalled with `python3 -m shelloracle` - this command should fail
3. `pip3 install shelloracle`
4. `shor --init`

**Comment by odarcan** [comment]
Successfully installed shelloracle-0.5.0

0.5.0

**shor --init**
Traceback (most recent call last):
  File "/home/x/.local/bin/shor", line 8, in <module>
    sys.exit(main())
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/__main__.py", line 17, in main
    bootstrap()
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/bootstrap.py", line 79, in bootstrap
    if not (shells := get_installed_shells()):
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/bootstrap.py", line 29, in get_installed_shells
    if subprocess.run(["command", "-v", shell], stdout=subprocess.DEVNULL):
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'command'

**Comment by djcopley** [comment]
It isn't installing the new version which is 0.5.1.

Try: `pip3 install --upgrade shelloracle`

**Comment by odarcan** [comment]
It upgraded it now
Now it did some other things!

**python3 -m shelloracle --init**
Enable terminal keybindings and update rc? ([y]/n) y
Successfully wrote key bindings to ~/.shelloracle.bash
Successfully updated ~/.bashrc

how do I run it

**Comment by djcopley** [comment]
Perfect! Now either restart your terminal or run `source ~/.bashrc`. That will enable keybindings.

Press CTRL+F to open the prompt.

All of the rest of the usage steps can be found in the [README](https://github.com/djcopley/ShellOracle/blob/main/README.md).

**Comment by odarcan** [comment]
typing Cntrl+F gives this:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/__main__.py", line 24, in <module>
    main()
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/__main__.py", line 20, in main
    shelloracle.cli()
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/shelloracle.py", line 66, in cli
    asyncio.run(shell_oracle())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/shelloracle.py", line 49, in shell_oracle
    provider = get_provider(config.global_config.provider)()
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/provider.py", line 38, in get_provider
    from .providers import Ollama, OpenAI
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/providers/__init__.py", line 2, in <module>
    from .openai import OpenAI
  File "/home/x/.local/lib/python3.10/site-packages/shelloracle/providers/openai.py", line 4, in <module>
    from openai import AsyncOpenAI as OpenAIClient
ImportError: cannot import name 'AsyncOpenAI' from 'openai' (/home/x/.local/lib/python3.10/site-packages/openai/__init__.py)

**Comment by djcopley** [comment]
Will you open this as a new issue? These are all good finds. Linux mint has not been tested yet so you are definitely the guinea pig :P

**Comment by odarcan** [comment]
I hope you make any sense of these because I dont I just want my shell to understand me more :)

Ill continue tomorrow
