### ISSUE TITLE
new issues

### ISSUE THREAD

**Issue by odarcan** [djcopley/ShellOracle#43]
I have now a fresh install Linux Mint 21.3
this is the error I get when I do cntrl F 
I dont use python much so I think full instructions should be provided, and all dependencies should be installed with the package, or maybe have an installation script like the ollama thing,
or maybe check for packages if they exist and give error and explain the problem before the wall of text.

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/osman/.local/lib/python3.10/site-packages/shelloracle/__main__.py", line 24, in <module>
    main()
  File "/home/osman/.local/lib/python3.10/site-packages/shelloracle/__main__.py", line 20, in main
    shelloracle.cli()
  File "/home/osman/.local/lib/python3.10/site-packages/shelloracle/shelloracle.py", line 66, in cli
    asyncio.run(shell_oracle())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/osman/.local/lib/python3.10/site-packages/shelloracle/shelloracle.py", line 49, in shell_oracle
    provider = get_provider(config.global_config.provider)()
  File "/home/osman/.local/lib/python3.10/site-packages/shelloracle/provider.py", line 38, in get_provider
    from .providers import Ollama, OpenAI
  File "/home/osman/.local/lib/python3.10/site-packages/shelloracle/providers/__init__.py", line 2, in <module>
    from .openai import OpenAI
  File "/home/osman/.local/lib/python3.10/site-packages/shelloracle/providers/openai.py", line 4, in <module>
    from openai import AsyncOpenAI as OpenAIClient
ImportError: cannot import name 'AsyncOpenAI' from 'openai' (/home/osman/.local/lib/python3.10/site-packages/openai/__init__.py)

**Comment by djcopley** [comment]
@odarcan Send me an email at djcopley@proton.me if you want help debugging
